### ISSUE TITLE
A few changes to the spec

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/ndx-ibl#1]
IblSessionData
	session_data.subject - > Subject.subject_id
	session_data.procedures -> NWBFile.session_description
	session_data.number -> NWBFile.session_id
	session_data.narrative -> NWBFile.notes
	session_data.end_type needs to be a date time (Low priority)

IblSubject should keep the name=“subject” of the Subject class it inherited from
	Subject.death_date should be a datetime (Low priority)

**Comment by bendichter** [comment]
add json field and water admin

**Comment by Saksham20** [comment]
changing the 'dtype' as 'datetime' and then creating the nwbfile gives this error, I remember getting this long back so I kept the datetime as a str dtype
```
Traceback (most recent call last):
  File "C:\Users\luna\Documents\NWB\ndx-ibl-metadata\venv\lib\site-packages\hdmf\build\objectmapper.py", line 850, in __add_datasets
    data, dtype = self.convert_dtype(spec, attr_value)
  File "C:\Users\luna\Documents\NWB\ndx-ibl-metadata\venv\lib\site-packages\hdmf\build\objectmapper.py", line 193, in convert_dtype
    ret, ret_dtype = cls.__check_edgecases(spec, value, spec_dtype)
  File "C:\Users\luna\Documents\NWB\ndx-ibl-metadata\venv\lib\site-packages\hdmf\build\objectmapper.py", line 299, in __check_edgecases
    raise ValueError(msg)
ValueError: unrecognized dtype: datetime -- cannot convert value
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "C:\Users\luna\Documents\NWB\ndx-ibl-metadata\venv\lib\site-packages\hdmf\utils.py", line 561, in func_call
    return func(args[0], **pargs)
  File "C:\Users\luna\Documents\NWB\ndx-ibl-metadata\venv\lib\site-packages\hdmf\backends\hdf5\h5tools.py", line 323, in write
    call_docval_func(super().write, kwargs)
  File "C:\Users\luna\Documents\NWB\ndx-ibl-metadata\venv\lib\site-packages\hdmf\utils.py", line 405, in call_docval_func
    return func(*fargs, **fkwargs)
  File "C:\Users\luna\Documents\NWB\ndx-ibl-metadata\venv\lib\site-packages\hdmf\utils.py", line 561, in func_call
    return func(args[0], **pargs)
  File "C:\Users\luna\Documents\NWB\ndx-ibl-metadata\venv\lib\site-packages\hdmf\backends\io.py", line 44, in write
    f_builder = self.__manager.build(container, source=self.__source)
  File "C:\Users\luna\Documents\NWB\ndx-ibl-metadata\venv\lib\site-packages\hdmf\utils.py", line 561, in func_call
    return func(args[0], **pargs)
  File "C:\Users\luna\Documents\NWB\ndx-ibl-metadata\venv\lib\site-packages\hdmf\build\manager.py", line 166, in build
    result = self.__type_map.build(container, self, source=source, spec_ext=spec_ext, export=export)
  File "C:\Users\luna\Documents\NWB\ndx-ibl-metadata\venv\lib\site-packages\hdmf\utils.py", line 561, in func_call
    return func(args[0], **pargs)
  File "C:\Users\luna\Documents\NWB\ndx-ibl-metadata\venv\lib\site-packages\hdmf\build\manager.py", line 832, in build
    builder = obj_mapper.build(container, manager, builder=builder, source=source, spec_ext=spec_ext, export=export)
  File "C:\Users\luna\Documents\NWB\ndx-ibl-metadata\venv\lib\site-packages\hdmf\utils.py", line 561, in func_call
    return func(args[0], **pargs)
  File "C:\Users\luna\Documents\NWB\ndx-ibl-metadata\venv\lib\site-packages\hdmf\build\objectmapper.py", line 608, in build
    self.__add_groups(builder, self.__spec.groups, container, manager, source, export)
  File "C:\Users\luna\Documents\NWB\ndx-ibl-metadata\venv\lib\site-packages\hdmf\build\objectmapper.py", line 893, in __add_groups
    self.__add_groups(sub_builder, spec.groups, container, build_manager, source, export)
  File "C:\Users\luna\Documents\NWB\ndx-ibl-metadata\venv\lib\site-packages\hdmf\build\objectmapper.py", line 917, in __add_groups
    self.__add_containers(builder, spec, attr_value, build_manager, source, container, export)
  File "C:\Users\luna\Documents\NWB\ndx-ibl-metadata\venv\lib\site-packages\hdmf\build\objectmapper.py", line 990, in __add_containers
    self.__add_containers(builder, spec, container, build_manager, source, parent_container, export)
  File "C:\Users\luna\Documents\NWB\ndx-ibl-metadata\venv\lib\site-packages\hdmf\build\objectmapper.py", line 937, in __add_containers
    rendered_obj = build_manager.build(value, source=source, spec_ext=spec, export=export)
  File "C:\Users\luna\Documents\NWB\ndx-ibl-metadata\venv\lib\site-packages\hdmf\utils.py", line 561, in func_call
    return func(args[0], **pargs)
  File "C:\Users\luna\Documents\NWB\ndx-ibl-metadata\venv\lib\site-packages\hdmf\build\manager.py", line 166, in build
    result = self.__type_map.build(container, self, source=source, spec_ext=spec_ext, export=export)
  File "C:\Users\luna\Documents\NWB\ndx-ibl-metadata\venv\lib\site-packages\hdmf\utils.py", line 561, in func_call
    return func(args[0], **pargs)
  File "C:\Users\luna\Documents\NWB\ndx-ibl-metadata\venv\lib\site-packages\hdmf\build\manager.py", line 832, in build
    builder = obj_mapper.build(container, manager, builder=builder, source=source, spec_ext=spec_ext, export=export)
  File "C:\Users\luna\Documents\NWB\ndx-ibl-metadata\venv\lib\site-packages\hdmf\utils.py", line 561, in func_call
    return func(args[0], **pargs)
  File "C:\Users\luna\Documents\NWB\ndx-ibl-metadata\venv\lib\site-packages\hdmf\build\objectmapper.py", line 607, in build
    self.__add_datasets(builder, self.__spec.datasets, container, manager, source, export)
  File "C:\Users\luna\Documents\NWB\ndx-ibl-metadata\venv\lib\site-packages\hdmf\build\objectmapper.py", line 854, in __add_datasets
    raise Exception(msg) from ex
Exception: could not convert 'end_time' for IblSessionData 'Ibl_session_data'
```

**Comment by bendichter** [comment]
mostly done.

IblSessionData
session_data.subject  has been removed
session_data.procedures -> NWBFile.session_description (done)
session_data.number -> NWBFile.session_id (done)
session_data.narrative -> NWBFile.notes (done)
session_data.end_type needs to be a date time (has error)

IblSubject should keep the name=“subject” of the Subject class it inherited from
Subject.death_date should be a datetime (Low priority)
